# Generated by Django 3.2 on 2021-04-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='describtion',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
